# Generated by Django 5.1.4 on 2026-07-29 00:07

import apps.core.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProdukKoperasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_produk', models.CharField(max_length=200)),
                ('deskripsi', models.TextField(blank=True)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=12)),
                ('foto', models.ImageField(blank=True, null=True, storage=apps.core.storage_backends.CloudinaryImageStorage(), upload_to='koperasi/')),
                ('status', models.CharField(choices=[('tersedia', 'Tersedia'), ('habis', 'Habis')], default='tersedia', max_length=20)),
                ('link_gform_pesan', models.URLField(blank=True, help_text='Link Google Form untuk pemesanan produk ini')),
            ],
            options={
                'verbose_name': 'Produk Koperasi',
                'verbose_name_plural': 'Produk Koperasi',
                'ordering': ['nama_produk'],
            },
        ),
    ]
