# Generated by Django 5.1.4 on 2026-07-29 00:07

import apps.core.storage_backends
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pengurus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, storage=apps.core.storage_backends.CloudinaryImageStorage(), upload_to='pengurus/')),
                ('bidang', models.PositiveSmallIntegerField(choices=[(1, 'Inti'), (2, 'Badan Pengurus Harian'), (3, 'Bidang I Pendidikan dan Penalaran'), (4, 'Bidang II Minat dan Bakat'), (5, 'Bidang III Kewirausahaan dan Kesejahteraan Mahasiswa'), (6, 'Bidang IV Pengabdian Masyarakat'), (7, 'Bidang V Komunikasi dan Informasi')], default=1)),
                ('jabatan', models.PositiveSmallIntegerField(choices=[(1, 'Ketua'), (2, 'Wakil Ketua'), (3, 'Sekretaris'), (4, 'Bendahara'), (5, 'Koordinator Bidang'), (6, 'Staff')], default=6)),
            ],
            options={
                'verbose_name': 'Pengurus',
                'verbose_name_plural': 'Pengurus',
                'ordering': ['bidang', 'jabatan', 'nama'],
            },
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sejarah', models.TextField(blank=True)),
                ('visi', models.TextField(blank=True)),
                ('periode_kepengurusan', models.CharField(blank=True, help_text='Contoh: 2023/2024', max_length=9)),
                ('logo', models.ImageField(blank=True, null=True, storage=apps.core.storage_backends.CloudinaryImageStorage(), upload_to='profil/')),
            ],
            options={
                'verbose_name': 'Profil HIMATIKA',
                'verbose_name_plural': 'Profil HIMATIKA',
            },
        ),
        migrations.CreateModel(
            name='ProgramKerja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_proker', models.CharField(max_length=200)),
                ('deskripsi', models.TextField()),
                ('bidang', models.PositiveSmallIntegerField(choices=[(1, 'Inti'), (2, 'Badan Pengurus Harian'), (3, 'Bidang I Pendidikan dan Penalaran'), (4, 'Bidang II Minat dan Bakat'), (5, 'Bidang III Kewirausahaan dan Kesejahteraan Mahasiswa'), (6, 'Bidang IV Pengabdian Masyarakat'), (7, 'Bidang V Komunikasi dan Informasi')], default=1)),
                ('progres', models.PositiveIntegerField(default=0, help_text='Persentase progres (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'verbose_name': 'Program Kerja',
                'verbose_name_plural': 'Program Kerja',
                'ordering': ['progres'],
            },
        ),
        migrations.CreateModel(
            name='Misi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urutan', models.PositiveSmallIntegerField(help_text='Urutan misi (1, 2, 3, ...)')),
                ('deskripsi', models.TextField()),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='misi', to='profil.profil')),
            ],
            options={
                'verbose_name': 'Misi',
                'verbose_name_plural': 'Misi',
            },
        ),
        migrations.CreateModel(
            name='FilosofiLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('profil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filosofi', to='profil.profil')),
            ],
            options={
                'verbose_name': 'Filosofi Logo',
                'verbose_name_plural': 'Filosofi Logo',
            },
        ),
    ]
