# Generated by Django 5.1.4 on 2026-08-13 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PengaturanWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_website', models.CharField(default='HIMATIKA Universitas Udayana', max_length=100)),
                ('alamat', models.TextField(blank=True)),
                ('instagram_link', models.URLField(blank=True)),
                ('facebook_link', models.URLField(blank=True)),
                ('spotify_link', models.URLField(blank=True)),
                ('youtube_link', models.URLField(blank=True)),
                ('website_link', models.URLField(blank=True)),
                ('email_kontak', models.EmailField(blank=True, max_length=254)),
                ('no_hp', models.CharField(blank=True, max_length=20)),
                ('whatsapp_pj_koperasi', models.CharField(blank=True, help_text='Nomor WA PJ untuk konfirmasi pesanan koperasi', max_length=20)),
            ],
            options={
                'verbose_name': 'Pengaturan Website',
                'verbose_name_plural': 'Pengaturan Website',
            },
        ),
    ]
