# Generated by Django 5.1.4 on 2026-08-13 06:06

from django.db import migrations


def copy_pengaturan_data(apps, schema_editor):
    """Kopi data dari pengaturan_pengaturanwebsite ke profil_pengaturanwebsite"""
    from django.db import connection

    if "pengaturan_pengaturanwebsite" not in connection.introspection.table_names():
        return

    cursor = connection.cursor()
    
    # Kopi data dari table lama ke table baru
    cursor.execute("""
        INSERT INTO profil_pengaturanwebsite (id, nama_website, alamat, instagram_link, facebook_link, spotify_link, youtube_link, website_link, email_kontak, no_hp, whatsapp_pj_koperasi)
        SELECT id, nama_website, alamat, instagram_link, facebook_link, spotify_link, youtube_link, website_link, email_kontak, no_hp, whatsapp_pj_koperasi
        FROM pengaturan_pengaturanwebsite
        WHERE id NOT IN (SELECT id FROM profil_pengaturanwebsite)
    """)


def reverse_copy(apps, schema_editor):
    """Reverse operation - hapus data yang dikopi"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0002_pengaturanwebsite'),
    ]

    operations = [
        migrations.RunPython(copy_pengaturan_data, reverse_copy),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS pengaturan_pengaturanwebsite",
            reverse_sql="",
        ),
        migrations.RunSQL(
            sql="DELETE FROM django_migrations WHERE app='pengaturan'",
            reverse_sql="",
        ),
    ]
