# Generated by Django 5.1.4 on 2026-08-13 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0003_migrate_pengaturan_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='misi',
            options={'ordering': ['urutan'], 'verbose_name': 'Misi', 'verbose_name_plural': 'Misi'},
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.PositiveIntegerField(help_text='Tahun kejadian')),
                ('judul', models.CharField(max_length=200)),
                ('deskripsi', models.TextField()),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='profil.profil')),
            ],
            options={
                'verbose_name': 'Timeline',
                'verbose_name_plural': 'Timeline',
                'ordering': ['-tahun'],
            },
        ),
    ]
