# Generated by Django 5.1.4 on 2026-08-18 12:20

import apps.core.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0004_alter_misi_options_timeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='programkerja',
            name='foto',
            field=models.ImageField(blank=True, null=True, storage=apps.core.storage_backends.CloudinaryImageStorage(), upload_to='program-kerja/'),
        ),
    ]
