# Generated by Django 5.1.4 on 2026-08-18 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0005_programkerja_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengaturanwebsite',
            name='statistik_1_label',
            field=models.CharField(default='Anggota Aktif', max_length=100),
        ),
        migrations.AddField(
            model_name='pengaturanwebsite',
            name='statistik_1_nilai',
            field=models.CharField(default='300+', max_length=50),
        ),
        migrations.AddField(
            model_name='pengaturanwebsite',
            name='statistik_2_label',
            field=models.CharField(default='Prestasi Diraih', max_length=100),
        ),
        migrations.AddField(
            model_name='pengaturanwebsite',
            name='statistik_2_nilai',
            field=models.CharField(default='50+', max_length=50),
        ),
        migrations.AddField(
            model_name='pengaturanwebsite',
            name='statistik_3_label',
            field=models.CharField(default='Program Kerja', max_length=100),
        ),
        migrations.AddField(
            model_name='pengaturanwebsite',
            name='statistik_3_nilai',
            field=models.CharField(default='20+', max_length=50),
        ),
        migrations.AddField(
            model_name='pengaturanwebsite',
            name='statistik_4_label',
            field=models.CharField(default='Berdiri Sejak', max_length=100),
        ),
        migrations.AddField(
            model_name='pengaturanwebsite',
            name='statistik_4_nilai',
            field=models.CharField(default='1998', max_length=50),
        ),
    ]
