# Generated by Django 5.1.4 on 2026-07-29 00:07

import apps.core.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pertanyaan', models.CharField(max_length=255)),
                ('jawaban', models.TextField()),
                ('urutan', models.PositiveIntegerField(default=0)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ['urutan'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(choices=[('pengumuman', 'Pengumuman'), ('open-requirement', 'Open Requirement'), ('event', 'Event'), ('prestasi', 'Prestasi'), ('mathpedia', 'Mathpedia')], default='pengumuman', max_length=20)),
                ('judul', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('konten', models.TextField()),
                ('thumbnail', models.ImageField(blank=True, null=True, storage=apps.core.storage_backends.CloudinaryImageStorage(), upload_to='post/')),
                ('penulis', models.CharField(max_length=100)),
                ('email_penulis', models.EmailField(blank=True, max_length=100, null=True)),
                ('ig_penulis', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('tanggal_publish', models.DateTimeField(blank=True, null=True)),
                ('tanggal_diubah', models.DateTimeField(auto_now=True)),
                ('tanggal_event', models.DateField(blank=True, null=True)),
                ('lokasi_event', models.CharField(blank=True, max_length=255, null=True)),
                ('link_formulir', models.URLField(blank=True, max_length=255, null=True)),
                ('deadline_formulir', models.DateField(blank=True, null=True)),
                ('level_prestasi', models.CharField(blank=True, choices=[('internasional', 'Internasional'), ('nasional', 'Nasional'), ('lokal', 'Lokal')], max_length=20, null=True)),
                ('kategori_mathpedia', models.CharField(blank=True, choices=[('aljabar', 'Aljabar'), ('geometri', 'Geometri'), ('kalkulus', 'Kalkulus'), ('analisis', 'Analisis'), ('matematika-diskrit', 'Matematika Diskrit'), ('peluang', 'Peluang'), ('statistika', 'Statistika'), ('lainnya', 'Lainnya')], help_text='hanya digunakan jika tipe mathpedia', max_length=30, null=True)),
            ],
            options={
                'ordering': ['-status', '-tanggal_dibuat', '-tanggal_publish'],
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.PositiveIntegerField()),
                ('gambar', models.ImageField(storage=apps.core.storage_backends.CloudinaryImageStorage(), upload_to='post/')),
                ('caption', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Gambar Artikel',
                'verbose_name_plural': 'Gambar Artikel',
                'ordering': ['nomor'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tag',
                'ordering': ['nama'],
            },
        ),
    ]
