# Generated by Django 5.1.4 on 2026-07-29 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('konten', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='konten.post'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='konten.tag'),
        ),
        migrations.AlterUniqueTogether(
            name='postimage',
            unique_together={('post', 'nomor')},
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['tipe'], name='konten_post_tipe_fc46c0_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status'], name='konten_post_status_73586a_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['tanggal_publish'], name='konten_post_tanggal_a6342a_idx'),
        ),
    ]
