# Generated by Django 5.1.4 on 2026-08-05 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('konten', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQ'},
        ),
        migrations.RemoveField(
            model_name='faq',
            name='aktif',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='urutan',
        ),
    ]
