# Generated by Django 5.1.4 on 2026-08-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("konten", "0003_alter_faq_options_remove_faq_aktif_remove_faq_urutan"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="ringkasan",
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]