# Generated by Django 5.1.4 on 2026-07-29 00:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriAspirasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urutan', models.PositiveIntegerField(help_text='Urutan kategori aspirasi (1, 2, 3, ...)')),
                ('nama_kategori', models.CharField(max_length=100)),
                ('deskripsi', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Kategori Aspirasi',
                'verbose_name_plural': 'Kategori Aspirasi',
                'ordering': ['urutan'],
            },
        ),
        migrations.CreateModel(
            name='RamaSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Kode anonim responden.', unique=True)),
                ('tanggal_submit', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('tersimpan', 'Tersimpan'), ('terkirim', 'Terkirim ke Google Sheet'), ('gagal', 'Gagal Sinkronisasi')], default='tersimpan', max_length=20)),
            ],
            options={
                'verbose_name': 'Pengisian RAMA',
                'verbose_name_plural': 'Pengisian RAMA',
                'ordering': ['-tanggal_submit'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun_ajaran', models.CharField(help_text='Contoh: 2025/2026', max_length=9)),
                ('jenis', models.CharField(choices=[('ganjil', 'Ganjil'), ('genap', 'Genap')], max_length=10)),
                ('aktif', models.BooleanField(default=False, help_text='Hanya boleh ada satu semester aktif.')),
            ],
            options={
                'verbose_name': 'Semester',
                'verbose_name_plural': 'Semester',
                'ordering': ['-tahun_ajaran', 'jenis'],
            },
        ),
        migrations.CreateModel(
            name='RamaAspirasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kepuasan', models.PositiveSmallIntegerField(choices=[(1, 'Sangat Tidak Puas'), (2, 'Tidak Puas'), (3, 'Cukup'), (4, 'Puas'), (5, 'Sangat Puas')])),
                ('isi_aspirasi', models.TextField()),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aspirasi', to='rama.kategoriaspirasi')),
            ],
            options={
                'verbose_name': 'Aspirasi RAMA',
                'verbose_name_plural': 'Aspirasi RAMA',
                'ordering': ['kategori__urutan'],
            },
        ),
    ]
