# Generated by Django 5.1.4 on 2026-07-29 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rama', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ramasubmission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rama_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ramaaspirasi',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aspirasi', to='rama.ramasubmission'),
        ),
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.UniqueConstraint(fields=('tahun_ajaran', 'jenis'), name='unique_semester'),
        ),
        migrations.AddField(
            model_name='ramasubmission',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='rama.semester'),
        ),
        migrations.AddIndex(
            model_name='ramaaspirasi',
            index=models.Index(fields=['kategori'], name='rama_ramaas_kategor_8f0cb2_idx'),
        ),
        migrations.AddConstraint(
            model_name='ramaaspirasi',
            constraint=models.UniqueConstraint(fields=('submission', 'kategori'), name='unique_submission_kategori'),
        ),
        migrations.AddIndex(
            model_name='ramasubmission',
            index=models.Index(fields=['semester'], name='rama_ramasu_semeste_a68311_idx'),
        ),
        migrations.AddIndex(
            model_name='ramasubmission',
            index=models.Index(fields=['status'], name='rama_ramasu_status_a498a4_idx'),
        ),
        migrations.AddIndex(
            model_name='ramasubmission',
            index=models.Index(fields=['tanggal_submit'], name='rama_ramasu_tanggal_1b045d_idx'),
        ),
        migrations.AddConstraint(
            model_name='ramasubmission',
            constraint=models.UniqueConstraint(fields=('user', 'semester'), name='unique_user_semester_submission'),
        ),
    ]
