# Generated by Django 5.1.4 on 2026-07-29 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arsip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(choices=[('soal', 'Arsip Soal'), ('materi', 'Materi Perkuliahan')], max_length=20)),
                ('judul', models.CharField(max_length=200)),
                ('link_gdrive', models.URLField(help_text='Link Google Drive yang dapat diakses.')),
                ('tahun', models.PositiveIntegerField()),
                ('semester', models.CharField(choices=[('ganjil', 'Ganjil'), ('genap', 'Genap')], max_length=10)),
                ('dosen', models.CharField(blank=True, max_length=100)),
                ('deskripsi', models.TextField(blank=True)),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Arsip Soal & Materi',
                'verbose_name_plural': 'Arsip Soal & Materi',
                'ordering': ['-tahun', '-tanggal_upload'],
            },
        ),
        migrations.CreateModel(
            name='MataKuliah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Mata Kuliah',
                'verbose_name_plural': 'Mata Kuliah',
                'ordering': ['kode'],
            },
        ),
    ]
