# Generated by Django 5.1.4 on 2026-07-29 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arsip', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='arsip',
            name='diunggah_oleh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arsip_kuliah', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='arsip',
            name='mata_kuliah',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arsip', to='arsip.matakuliah'),
        ),
        migrations.AddIndex(
            model_name='arsip',
            index=models.Index(fields=['tipe'], name='arsip_arsip_tipe_643b57_idx'),
        ),
        migrations.AddIndex(
            model_name='arsip',
            index=models.Index(fields=['mata_kuliah'], name='arsip_arsip_mata_ku_522155_idx'),
        ),
        migrations.AddIndex(
            model_name='arsip',
            index=models.Index(fields=['tahun'], name='arsip_arsip_tahun_9acfa9_idx'),
        ),
        migrations.AddIndex(
            model_name='arsip',
            index=models.Index(fields=['semester'], name='arsip_arsip_semeste_c56c3e_idx'),
        ),
    ]
