# Generated by Django 5.1.4 on 2026-07-29 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jawaban_dipilih', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Jawaban Kuis',
                'verbose_name_plural': 'Jawaban Kuis',
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skor', models.PositiveIntegerField(default=0, help_text='Nilai akhir dalam persen (0-100)')),
                ('total_poin', models.PositiveIntegerField(default=0, help_text='Total poin yang didapat dari jawaban benar di attempt ini')),
                ('waktu_mulai', models.DateTimeField(auto_now_add=True)),
                ('waktu_selesai', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('berlangsung', 'Berlangsung'), ('selesai', 'Selesai')], default='berlangsung', max_length=20)),
            ],
            options={
                'verbose_name': 'Percobaan Kuis',
                'verbose_name_plural': 'Percobaan Kuis',
                'ordering': ['-waktu_mulai'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urutan', models.PositiveIntegerField(default=1)),
                ('tipe', models.CharField(choices=[('pg', 'Pilihan Ganda'), ('isian', 'Isian Singkat')], default='pg', max_length=10)),
                ('teks_soal', models.TextField()),
                ('poin', models.PositiveIntegerField(default=10, help_text='Poin yang diperoleh jika soal dijawab benar.')),
                ('pilihan_a', models.CharField(blank=True, max_length=255)),
                ('pilihan_b', models.CharField(blank=True, max_length=255)),
                ('pilihan_c', models.CharField(blank=True, max_length=255)),
                ('pilihan_d', models.CharField(blank=True, max_length=255)),
                ('pilihan_e', models.CharField(blank=True, max_length=255)),
                ('jawaban_benar_pg', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1)),
                ('jawaban_benar_isian', models.CharField(blank=True, help_text='Tidak membedakan huruf besar-kecil.', max_length=255)),
            ],
            options={
                'verbose_name': 'Soal Kuis',
                'verbose_name_plural': 'Soal Kuis',
                'ordering': ['urutan'],
            },
        ),
        migrations.CreateModel(
            name='QuizSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('deskripsi', models.TextField(blank=True)),
                ('topik', models.CharField(blank=True, help_text='Contoh: Kalkulus, Aljabar Linear', max_length=100)),
                ('level_kesulitan', models.CharField(choices=[('mudah', 'Mudah'), ('menengah', 'Menengah'), ('sulit', 'Sulit')], default='mudah', max_length=20)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Set Kuis',
                'verbose_name_plural': 'Set Kuis',
                'ordering': ['judul'],
            },
        ),
        migrations.CreateModel(
            name='UserPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_poin', models.PositiveIntegerField(default=0)),
                ('total_quiz', models.PositiveIntegerField(default=0, help_text='Jumlah quiz_set berbeda yang sudah diselesaikan')),
                ('total_benar', models.PositiveIntegerField(default=0, help_text='Total jawaban benar, dihitung dari attempt TERBAIK tiap quiz_set')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Poin Pengguna',
                'verbose_name_plural': 'Poin Pengguna',
                'ordering': ['-total_poin'],
            },
        ),
    ]
