# Generated by Django 5.1.4 on 2026-07-29 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mathquiz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jawaban', to='mathquiz.quizattempt'),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jawaban_masuk', to='mathquiz.quizquestion'),
        ),
        migrations.AddField(
            model_name='quizset',
            name='dibuat_oleh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_set_dibuat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='quiz_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soal', to='mathquiz.quizset'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='quiz_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='mathquiz.quizset'),
        ),
        migrations.AddField(
            model_name='userpoint',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='point', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='quizanswer',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='unique_jawaban_per_soal_per_attempt'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['user'], name='mathquiz_qu_user_id_48a45e_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['quiz_set'], name='mathquiz_qu_quiz_se_411d0e_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['status'], name='mathquiz_qu_status_9f0fcd_idx'),
        ),
    ]
